name: coufeedback
description: CoU user feedback/suggestion/report form
version: 0.0.2

dependencies:
  browser: any
  polymer: ">=0.16.1+4 <0.17.0"
  transmit: 1.1.0

transformers:
  - polymer:
      entry_points: web/test.html